version: "3"
services:
  cricket-client:
    image: cricket-client
    stdin_open: true
    ports:
      - "3000:3000"
  cricket-api:
    image: cricket-api
    stdin_open: true
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
