version: "3"
services:
  api-server:
    image: api-server
    stdin_open: true
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - "27018:27018"
