version: "3"
services:
  cricket-client:
    image: cricket-client
    stdin_open: true
    ports:
      - "3000:3000"
  cricket-api:
    image: cricket-api
    stdin_open: true
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
  rabitmq:
    image: rabbitmq:3.8-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
      - 61614:61613
      - 15675:15674
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs

networks:
  rabbitmq_nodejs:
    driver: bridge
